{% set version = "2018.0.3" %}
{% set vtag = "2018_U3" %}
{% set args = " --build-args='stdver=c++11 -march=native -mtune=native -DTBB_USE_GCC_BUILTINS=1 -D__TBB_64BIT_ATOMICS=0' --make-tool="make -j4" --install-libs --install-devel --install-docs" %}
#  no --install-python yet, it will be a separate package

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ vtag }}_oss_src.tgz
  url: https://github.com/01org/tbb/archive/{{ vtag }}.tar.gz
  sha256: 23793c8645480148e9559df96b386b780f92194c80120acce79fcdaae0d81f45

build:
  number: 0
  script: python build/build.py {{ args }}                                          # [unix]

requirements:
  build:
    - toolchain3-rpi3
    - python
    - swig
    - m2w64-make  # [win]

test:
  requires:
    - python
  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb.so.2']"  # [linux]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb${SHLIB_EXT}']"  # [unix and not linux]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library
  dev_url: https://github.com/01org/tbb
  doc_url: https://software.intel.com/en-us/node/506039

extra:
  recipe-maintainers:
    - jschueller
    - anton-malakhov
